language: python
python:
- '2.7'
- '3.6'
- nightly
install: pip install -r requirements/dev.txt
script: python -m pytest --cov=md_analytics tests/
after_success:
- pip install coveralls
- coverage run --source=md_analysis -q nosetests
- coveralls
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: eWfMAUbZnTXLRH6ASFrbWhkOvY25cSseUyDqiKP3LI2V3jQm2jovr+CFuCLZk5eimjUdEXFx20yPtGQPOLbGufbkDeozPvUQLRe9Pbs/ifU0E0/LVYuyes1yl8bJQwNsn+Q+N0i3sF1kp2T3RR60ryPx5ComyDVg9H5tS0M1spDF8HAtH7tFM+JuNTVruksmIOFuy7XU5mbrIk2gOSqKT2hhhfyIzOooNsWDHuSKYLaTwSarWpgpHntghsuQ9+Cd89ObT0+gJ5jtayyaBjuX78q40uLpNXICw4xXQflMiFzfWvAR+bnVIZysCMk5rz4ztZmFKm4BwCl6UFWsaJabPv1V1IsWy8Gm5vY756TLm6FV2pqLJCDVwssPZNJfLxVwxmCOZD2AaKcDpBAzwVk+tHnFfPRIiDe5vZFfSXtqkxtrYAAaU48Mj7Cn0BgrLjIxIixOY18LLlNJotiLP/pLEWPleBNwRP4uPjDu0O84JNzImIHFQkx4nPNdt96x224+JAY/DR04YXZ4lXz47BQ0nSu4vy3QQ2qpPfxMRaaowakSDmJXmbWBK9Cm3WC00rDRxhxyB59ZlY1QjdpI1H6cUg75eTkoOC7nbfUvoj0MwgqclWchgMxf5pg34IB2E4TFIOgdAd8dE58EK0Kflq22C5qtHdSzDV/AP0aAJmkMefg=
  app: md-analytics-stage
