language: python
python:
- '2.7'
- '3.6'
- nightly
install: pip install -r requirements/dev.txt
script: python -m pytest --cov=app/ tests/
# after_success:
# - pip install coveralls
# - coverage run --source=app/ -q nosetests
# - coveralls
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: KbcY6T7MqSpZ5zjKLsUxjqgP4b3BNTtn6sYl0qRuEJKSKjBdHBoOOP8k2GTTF3OsalExdKl+ZMdl3mU38zotPjgdPfv+ZHKwp7Ppf770GkBkogGybjaCl0k19BXe1LNG+/mgSnOap6rYQOtbM80fAja/XJKtmnmP8pKjbKssR1SKg7KuVlNQ0RbMC3xwr5G24kYBXc1gHJvf0XVkLokDjIO7hVUNeae3wOGeiE8aJAGrdwFURTtgzwkYN67ygYOIrsSJMzHecqhpMUPdqk3S9Ckvl7RtMIzJE+Z6YE0/4IDhGDCbF9BhgHR7/oEEuRNSuE709Hmr3qz1dGaBp0Cb85s8yyfa7mnvQjFjFC95GWcDGS6DbjfFjom5DjGvugU9UEuNV2AOOVTeYwuLAmWpd/hBI231FWCkabkmJVcjbgPgrr5PC1uK+AASEaLPMRYLJIpqe6gu4PH9CLn9BsLdXifAskvWnkbfeE/GlizuJAqv/YMsak0K+frVZ3FlfLgizfe51VnXrxoiqNPIwvWcIoyqqP5NBObu49oH52LdP462m6FBQf5Pi+LoIrSDq7DIXdeEjZ8WeFOyPBlWG4rkqyA004+TDN2TgiNG9xAgYlaE9Cdz55iA9fmlY02Uz1PgPi95LBKsZClHOMevrgKfCehwhvaoxOq7qtpIyLdVgQA=
  app: md-analytics-stage
